version: '3.5'
services:
    frontend:
        image: front-node-project
        ports:
          - 5000:5000
        container_name: frontend
        
    backend:
        image: back-go-project
        environment:
          - REDIS_HOST=redis
        ports:
          - 8080:8080
        container_name: backend  

    redis:
        image: redis:alpine
        container_name: redis
